### ISSUE TITLE
QAT找不到模型文件

### ISSUE THREAD

**Issue by CheungBH** [Jermmy/pytorch-quantization-demo#10]
你好。我运行QAT的时候，发现找不到模型文件：
Test set: Full Model Accuracy: 99%

Quantization bit: 8
Traceback (most recent call last):
  File "/Users/cheungbh/Desktop/pytorch-quantization-demo/quantization_aware_training.py", line 100, in <module>
    model.load_state_dict(torch.load(load_quant_model_file))
  File "/Users/cheungbh/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/Users/cheungbh/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/Users/cheungbh/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/mnist_cnnbn_qat.pt'

可是这个文件不是应该运行完才保存的嘛。这要怎么修改

**Comment by Jermmy** [comment]
您好，您的邮件已收到，我会尽快查看。

**Comment by Jermmy** [comment]
hello，把`load_quant_model_file`设置为`None`就可以了，之前忘了改。
