### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/mnist_cnnbn.pt'

### ISSUE THREAD

**Issue by yigengjiang** [Jermmy/pytorch-quantization-demo#25]
when i execute `python quantization_aware_training.py`, it outputs the error that:
```bash
Traceback (most recent call last):
  File "quantization_aware_training.py", line 81, in <module>
    model.load_state_dict(torch.load('ckpt/mnist_cnnbn.pt', map_location='cpu'))
  File "/home/jyg/anaconda3/envs/mixcompre/lib/python3.8/site-packages/torch/serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jyg/anaconda3/envs/mixcompre/lib/python3.8/site-packages/torch/serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jyg/anaconda3/envs/mixcompre/lib/python3.8/site-packages/torch/serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/mnist_cnnbn.pt'
```

**Comment by Jermmy** [comment]
Hi @yigengjiang , please train fp32 model first by `train.py`. After training, a fp32 model will be saved in `ckpt` folder, then you can using this model to run `quantization_aware_training.py`. Remenber to use the same `using_bn` variable in both fp32 training and qat.
